{{- if .Values.deployment_manager.enabled }}
{{- if .Values.postgresql.enabled }}
{{- if .Values.postgresql.deployment_manager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dialAdmin.deployment_manager.fullname" . }}-script-secret
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment_manager
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DEPLOYMENT_MANAGER_DATABASE: {{ include "dialAdmin.deployment_manager.database.name" . | b64enc }}
  DEPLOYMENT_MANAGER_USER: {{ include "dialAdmin.deployment_manager.database.user" . | b64enc | quote }}
  DEPLOYMENT_MANAGER_PASSWORD: {{  .Values.deployment_manager.configuration.datasource.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}