{{- if and .Values.deployment_manager.enabled .Values.deployment_manager.autoscaling.hpa.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "dialAdmin.deployment_manager.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.autoscaling.hpa.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.hpa.behavior | nindent 4 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "dialAdmin.deployment_manager.fullname" . }}
  minReplicas: {{ .Values.deployment_manager.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.deployment_manager.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .Values.deployment_manager.autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment_manager.autoscaling.hpa.targetMemory }}
    {{- end }}
    {{- if .Values.deployment_manager.autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment_manager.autoscaling.hpa.targetCPU }}
    {{- end }}
    {{- if .Values.deployment_manager.autoscaling.hpa.customRules -}}
      {{- toYaml .Values.deployment_manager.autoscaling.hpa.customRules | nindent 4 }}
    {{- end -}}
{{- end }}