{{- if and .Values.deployment_manager.enabled .Values.deployment_manager.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "dialAdmin.deployment_manager.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
  {{- if or .Values.deployment_manager.metrics.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.deployment_manager.metrics.service.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.deployment_manager.metrics.service.type }}
  {{- if and .Values.deployment_manager.metrics.service.clusterIP (eq .Values.deployment_manager.metrics.service.type "ClusterIP") }}
  clusterIP: {{ .Values.deployment_manager.metrics.service.clusterIP }}
  {{- end }}
  {{- if .Values.deployment_manager.metrics.service.sessionAffinity }}
  sessionAffinity: {{ .Values.deployment_manager.metrics.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.deployment_manager.metrics.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.deployment_manager.metrics.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.deployment_manager.metrics.service.type "LoadBalancer") (eq .Values.deployment_manager.metrics.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.deployment_manager.metrics.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.deployment_manager.metrics.service.type "LoadBalancer") (not (empty .Values.deployment_manager.metrics.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.deployment_manager.metrics.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.deployment_manager.metrics.service.type "LoadBalancer") (not (empty .Values.deployment_manager.metrics.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.deployment_manager.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http-metrics
      targetPort: http-metrics
      port: {{ .Values.deployment_manager.metrics.service.ports.http }}
      protocol: TCP
      {{- if (and (or (eq .Values.deployment_manager.metrics.service.type "NodePort") (eq .Values.deployment_manager.metrics.service.type "LoadBalancer")) (not (empty .Values.deployment_manager.metrics.service.nodePorts.http))) }}
      nodePort: {{ .Values.deployment_manager.metrics.service.nodePorts.http }}
      {{- else if eq .Values.deployment_manager.metrics.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.deployment_manager.metrics.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.deployment_manager.metrics.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.deployment_manager.podLabels .Values.commonLabels) "context" .) | fromYaml }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
{{- end }}