{{- if .Values.deployment_manager.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "dialAdmin.deployment_manager.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.deployment_manager.pdb.minAvailable }}
  minAvailable: {{ .Values.deployment_manager.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.deployment_manager.pdb.maxUnavailable ( not .Values.deployment_manager.pdb.minAvailable ) }}
  maxUnavailable: {{ .Values.deployment_manager.pdb.maxUnavailable | default 1 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.deployment_manager.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
