{{- if and .Values.deployment_manager.metrics.prometheusRule.enabled .Values.deployment_manager.enabled .Values.deployment_manager.metrics.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "dialAdmin.deployment_manager.fullname.namespace" . }}
  namespace: {{ default .Release.Namespace .Values.deployment_manager.metrics.prometheusRule.namespace | quote }}
    {{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.deployment_manager.metrics.prometheusRule.labels .Values.commonLabels) "context" .) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
    {{- if .Values.deployment_manager.metrics.prometheusRule.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.deployment_manager.metrics.prometheusRule.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: {{ include "common.names.fullname" . }}
    rules: {{- include "common.tplvalues.render" ( dict "value" .Values.deployment_manager.metrics.prometheusRule.rules "context" $ ) | nindent 6 }}
{{- end }}