{{- if and .Values.deployment_manager.enabled .Values.deployment_manager.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dialAdmin.deployment_manager.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.deployment_manager.secrets }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
  {{- end }}
{{- end }}