{{- if and .Values.deployment_manager.enabled .Values.deployment_manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dialAdmin.deployment_manager.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
  {{- if or .Values.deployment_manager.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.deployment_manager.serviceAccount.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.deployment_manager.serviceAccount.automountServiceAccountToken }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dialAdmin.deployment_manager.serviceAccountName" . }}-sa-secret
  namespace: {{ include "common.names.namespace" . | quote }}
labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: deployment-manager
  {{- if or .Values.deployment_manager.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.deployment_manager.serviceAccount.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
    kubernetes.io/service-account.name: {{ include "dialAdmin.deployment_manager.serviceAccountName" . }}
type: kubernetes.io/service-account-token
data:
  extra: ZHVtbXk=
{{- end }}